spring.application.name=user-portal-service
server.port=8082

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Spring Session Redis (多实例共享Session)
spring.session.store-type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

