spring.application.name=config-server
server.port=8888

# 本地 Git 仓库地址
spring.cloud.config.server.git.uri=file:///Users/fanjinchen/工程实践/Movies/Movies/config-repo
spring.cloud.config.server.git.default-label=main

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
